<?php

/**
 * @file
 * Primary module hooks for DateTimeasTimeZone module.
 */

/**
 * Implements hook_theme().
 */

function datetimeastimezone_theme($existing, $type, $theme, $path) {

  return [
    'datetime_as_timezone' => [
      'variables' => [
        'datetime' => NULL,
        'country' => NULL,
        'city' => NULL,
        'timezone' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */

function datetimeastimezone_page_attachments(array &$attachments) {
  
  $attachments['#attached']['library'][] = 'datetimeastimezone/datetime.zone';
}